
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Pasiya@2002
      MYSQL_DATABASE: library_management
      MYSQL_USER: root
      MYSQL_PASSWORD: Pasiya@2002
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: